#!/bin/bash
# needs openssh and keychain pkg

#gpg --full-generate-key 

## Walk through steps

#gpg --list-keys
#gpg --armor --export YOUR_KEY_ID

##Paste it into github or similar service

#git config --global user.email "you@example.com"
#git config --global user.name "Your Name"

#git config --global user.signingkey KEY_ID
#git config --global commit.gpgsign true

#ssh-keygen -t ed25519 -C "your_email@example.com"
#eval $(keychain --eval --quiet id_ed25519)
# this can be added to zshrc or similar 


