#!/bin/bash
curl -sSL https://codeberg.org/h8d13/ZUNO/raw/branch/master/asapsh | $ELEV bash
rm -f "$HOME"/.vscode-oss/extensions/extensions.json # will be regenerated on next launch with our extension inside
