#!/bin/bash
export ELEV="sudo"
export DEPS="curl wget tar zsh bash bash-completion firefox"

export PM="pacman"
export PM_CHECK_FLAG="-Q"
export PM_ADD_FLAGS="-Sy --noconfirm --needed"

export C_HOME="$HOME/.config/"
export L_HOME="$HOME/.local/"

export FIREFOX_DIR="/usr/lib/firefox"
export DIST_DIR="$FIREFOX_DIR/distribution"
export EXTENSIONS_DIR="$DIST_DIR/extensions"