#!/bin/bash
echo "Setting up distribution folder..."
$ELEV mkdir -p "$EXTENSIONS_DIR"
# Download uBlock Origin
echo "Downloading uBlock Origin..."
$ELEV wget -q -O "$EXTENSIONS_DIR/uBlock0@raymondhill.net.xpi" \
    "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"

$ELEV cp ./examples/policies.json "$DIST_DIR/policies.json"
